stages:
    - conventions
    - stylelint
    - eslint

stylelint:
    stage: stylelint
    image: pipelinecomponents/stylelint:0.9.0
    before_script:
        - apk add git
        - git clone -b v13.0.0-rg1 https://github.com/raccoongang/frontend.git
        - mv frontend/.stylelintrc .
    script:
        - stylelint '**/*.scss' --config .stylelintrc
    only:
        - merge_requests

commit_convention:
    stage: conventions
    image: node:12
    needs: []
    cache:
        key: commitlint-node_modules
        paths:
            - node_modules/
    before_script:
        - bash -c "[[ -d node_modules/ ]] || npm install @commitlint/cli @commitlint/config-conventional; exit 0;"
    script:
        - npx --quiet commitlint --from="$CI_MERGE_REQUEST_DIFF_BASE_SHA" --help-url 'https://raccoongang.atlassian.net/wiki/spaces/PSC/pages/2662006787/RG+Delivery+Solutions+Conventional+Commits'
    rules:
        - if: "$CI_MERGE_REQUEST_EVENT_TYPE != 'merge_train' && $CI_MERGE_REQUEST_DIFF_BASE_SHA"

eslint:
    stage: eslint
    image: node:12
    script:
        - npm i eslint eslint-config-edx
        - node_modules/eslint/bin/eslint.js lms/ cms/
    only:
        - merge_requests
