stages:
    - linting

stylelint:
    stage: linting
    image: pipelinecomponents/stylelint:0.9.0
    before_script:
        - apk add git
        - git clone https://github.com/raccoongang/frontend.git
        - mv frontend/.stylelintrc .
    script:
        - stylelint 'lms/**/*.scss' --config .stylelintrc
        - stylelint 'cms/**/*.scss' --config .stylelintrc
    only:
        - merge_requests
